---
title: "Homework 3"
subtitle: "BIOST 311"
author: "Taylor Okonek and Charlie Wolock"
date: \today
output: 
  pdf_document:
    toc: false
header-includes:
  - \usepackage{color}
  - \usepackage{fvextra}
  - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(formatR)

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(error = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(results = "hide")
```


## Instructions

This assignment should be submitted on Canvas as a .pdf by 12:30pm on Friday, April 22nd. You are welcome to work together on the homework; however, final solutions should be written up individually. 

Unedited software output in the body of your assignment is not acceptable. Please round numerical values to 2--3 significant digits, and include your R code (if applicable) in the same document. See the "How to Write a Proper Homework" document on Canvas for additional guidelines.  

Each homework assignment is worth 20 points total. Problems are graded for correctness, according to the number of points given in the problem statement. 

## 1. Transformations

For this question, we will be using the `births` dataset to explore transformations in linear regression. We are interested in the association between birth parent's weight prior to pregnancy and child's birth weight.

a. Load the `births` dataset (0 points)

b. The `wpre` variable gives birth parent's weight (in pounds) prior to pregnancy. Make a histogram to visualize the distribution of this variable with an appropriate number of bars. Would you describe the distribution as roughly symmetric, left skewed, or right skewed? (1 point)

c. Make two exploratory plots that could be used to visualize (1) the association between birth weight *in pounds* and weight prior to pregnancy and (2) the association between birth weight *in pounds* and *mean-centered* weight prior to pregnancy. How would you describe the relationship between birth weight and weight prior to pregnancy in each plot? Comparing the two plots, what is the same and what is different? Hint: 1 pounds = 453.592 grams. (2 points)

d. Perform a linear regression analysis to assess the linear association between weight prior to pregnancy (not mean-centered, our predictor) and birth weight in pounds (our outcome). Be sure to include a statistic quantifying this association with appropriate uncertainty quantification, as well as a hypothesis test. Be sure to state the null and alternative hypotheses. You should interpret your results; don't just give numerical output. (2 points)

e. Interpret the intercept estimate (in context) from the model you fit in part (d). Is the estimate for the intercept scientifically relevant? (1 point)

f. Fit a linear regression model to assess the linear association between mean-centered weight prior to pregnancy (our predictor) and birth weight in pounds (our outcome). Interpret the intercept estimate (in context). Is the estimate for the intercept scientifically relevant? Hint: there are a few ways to include a mean-centered variable in a linear regression model. Try googling to figure out an appropriate way to do so! (1 point)

g. The four traditional linear regression assumptions are linearity, independence, Normality of errors, and equal variance. For each of these assumptions, assess whether or not you think the assumption is violated for the model you fit in part (d). If appropriate, use graphs to support your argument. (1 point)

h. Suppose we are instead interested in making statements about multiplicative changes in weight prior to pregnancy and birth weight. Toward this end, make a histogram to visualize the distribution of log-transformed weight prior to pregnancy, with an appropriate number of bars. Would you describe the distribution as roughly symmetric, left skewed, or right skewed? (1 point)

i. Make an exploratory plot that could be used to visualize the association between birth weight in pounds and log weight prior to pregnancy. How would you describe the relationship between birth weight and log weight prior to pregnancy? (1 point)

j. Perform a linear regression analysis to assess the linear association between log weight prior to pregnancy (our predictor) and birth weight in pounds (our outcome). Be sure to include a statistic quantifying this association with appropriate uncertainty quantification, as well as a hypothesis test. Be sure to state the null and alternative hypotheses. You should interpret your results; don't just give numerical output. Hint: there are a few ways to include a logged variable in a linear regression model. Try googling to figure out an appropriate way to do so! (2 points)

k. Interpret the intercept estimate (in context) from the model you fit in part (j). Is the estimate for the intercept scientifically relevant? (1 point)

l. The four traditional linear regression assumptions are linearity, independence, Normality of errors, and equal variance. For each of these assumptions, assess whether or not you think the assumption is violated for the model you fit in part (j). If appropriate, use graphs to support your argument. (1 point)

m. Your friend believes that a model using log-transformed weight prior to pregnancy is more appropriate than a model using weight prior to pregnancy on its original scale, because the normality assumption will be better satisfied when quantitative variables are less skewed. Explain to your friend why their reasoning is not sufficient to justify using the model with log-transformed weight prior to pregnancy, regardless of how diagnostic plots appear. (1 point)

\newpage

## 2. Categorical predictors

a. The `age` variable gives birth parent's age (in years). Make a histogram to visualize the distribution of this variable with an appropriate number of bars. Would you describe the distribution as roughly symmetric, left skewed, or right skewed? (1 point)

b. Create a new categorical variable for age group in the `births` dataset. There should be three categories: (1) age less than 25 (2) age 25 - 34 (3) age 35 and over. Your categorical variable should contain groups "Under 25", "25-34", and "35 and over", respectively. Provide relevant descriptive statistics for the age group variable in either a table or sentences. (1 point)

c. Make a graph containing side-by-side boxplots comparing birth weight across these three different age groups. Make sure that ages are ordered from youngest to oldest, left to right (Hint: you can make age group a factor variable with levels in a particular order), and that the legend title is informative. (1 point)

d. Perform a linear regression analysis to assess the association between categorical age (our predictor) and birth weight in grams (our outcome). Interpret all coefficients in your model. State the null and alternative hypotheses for testing the association between categorical age and birth weight, and conduct this hypothesis test, reporting an appropriate p-value. For this question you do not need to report uncertainty. (2 points)

